# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Category.destroy_all

all_categories = {
  title: [
    "Happy Camper",
    "Dewey Decimal",
    "The Whisper",
    "Megaphone",
    "Sharp Acid",
    "The Madea",
    "Carpe Diem",
    "Oliver Twist",
    "Caffeinator",
    "Incinerator",
    "Silly String",
    "The Finicky",
    "Guru",
    "Aljazeera",
    "Spiffy style",
    "Champagne",
    "Social butterfly",
    "The Sunrise",
    "The Melancholic",
    "Ironic Clown"
  ],
  desc: [
    "Someone who never fails to have a smile on his or her face",
    "Most Well Organized",
    "Someone whose voice is hardly heard",
    "Someone that you always hear",
    "Someone whose remarks are always marked by sarcasm",
    "Someone who is dramatic over everything and anything",
    "For making the most of every day",
    "Someone who wants more of everything (Good or Bad)",
    "For the employee who drinks most coffee in a day",
    "For being ready to eat and drink anything",
    "For being the office prankster",
    "For being particular about their things",
    "For always getting us out of a difficult situation",
    "Somone who is always up to date with events around the world (News man)",
    "For appearing dapper most times",
    "For most sparkling personality",
    "For constantly surfing and tweeting",
    "First to get to the office",
    "Someone who is difficult to tell when he's happy or sad",
    "Someone who thinks he's funny but he's not"
  ],
  imageUrl: [
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776659/happy-camper_uzmukj.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776660/organized_znvzug.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466896500/whisper_ajlvlw.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466898785/megaphone_zxihbg.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466898614/sarcasm_sypwig.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776660/dramatic_o8apy5.png",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466894755/hardworker_myhcj3.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776661/oliver_w0tf2q.png",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776659/coffee-guy_f6ganj.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466894755/incinerator_qfqwyj.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776661/silly_bt2v16.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466894754/finicky-eater_e6h5bw.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776660/guru_kvfsbs.png",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466899059/news_ffc9c2.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466894754/dapper_tzqoog.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466894759/personality_gxgqbw.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466894756/social_butterfly_ik9i5w.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466894754/sunrise_dv6rrc.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776659/face_po1lr5.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776659/not_funny_d7xttu.jpg"
  ]
}

all_categories[:title].length.times do |index|
  Category.create(title: all_categories[:title][index], short_description: all_categories[:desc][index], imageUrl: all_categories[:imageUrl][index])
end


User.destroy_all

users = {
  email: [
    "abdulmalik.yusuf@andela.com",
    "abimbola.idowu@andela.com",
    "abiodun.shuaib@andela.com",
    "abisoye.atolagbe@andela.com",
    "adebayo.maborukoje@andela.com",
    "adebayo.adepoju@andela.com",
    "adeleke.togun@andela.com",
    "ahmed.onawale@andela.com",
    "ajibola.sogbein@andela.com",
    "akeem.oduola@andela.com",
    "akinjide.bankole@andela.com",
    "akonam.ikpelue@andela.com",
    "alex.obogbare@andela.com",
    "oluwakamiye.adelemoni@andela.com",
    "ayodeji.jayeoba@andela.com",
    "babajide.bello@andela.com",
    "babajide.fowotade@andela.com",
    "babatunde.mustapha@andela.com",
    "blessing.orazulume@andela.com",
    "blessing.ebowe@andela.com",
    "bodunde.adebiyi@andela.com",
    "bosom.azibayanami@andela.com ",
    "bukola.omotoso@andela.com",
    "bukola.makinwa@andela.com",
    "brice@andela.com",
    "chibuzor.obiora@andela.com",
    "chidi.ash@andela.com",
    "chidebere.nwocha@andela.com",
    "chidi.nnadi@andela.com",
    "chidozieiIieomah@andela.com",
    "chiemeka.alim@andela.com",
    "kingsley.edeh@andela.com",
    "chijioke.ndubisi@andela.com",
    "chinedu.daniel@andela.com",
    "damilola.omonori@andela.com",
    "daniel.james@andela.com",
    "debbie.enomah@andela.com",
    "dotun.owoade@andela.com",
    "ebun@andela.com",
    "emeka.ashikodi@andela.com",
    "emeka.osuagwu@andela.com",
    "emmanuel.akinyele@andela.com",
    "emmanuel.chigbo@andela.com",
    "emmanuel.isaac@andela.com",
    "eniola.arinde@andela.com",
    "tolulope.awoyemi@andela.com",
    "faical.tchirou@andela.com",
    "fiyinfoluwa.adebayo@andela.com ",
    "florence.okosun@andela.com",
    "franklin.ugwu@andela.com ",
    "gbolahan.okerayi@andela.com ",
    "gift.arisah@andela.com ",
    "godson.ukpere@andela.com",
    "george.james@andela.com",
    "helen.eboagwu@andela.com",
    "ibraheem.adeniyi@andela.com",
    "ifeanyi.oraelosi@andela.com",
    "ifedapo.olarewaju@andela.com",
    "ikem.okonkwo@andela.com",
    "ikenna.ekechi@andela.com",
    "innocent.amadi@andela.com",
    "issa.jubril@andela.com",
    "iyanu.durotola@andela.com",
    "e@andela.com",
    "johnson.ejezie@andela.com",
    "joshua.ugba@andela.com",
    "kayode.adeniyi@andela.com",
    "kehinde.ogunde@andela.com",
    "omowunmi.oni@andela.com",
    "kehinde.shittu@andela.com",
    "kolawole.erinoso@andela.com",
    "kosy.anyanwu@andela.com",
    "lawrence.bolutife@andela.com",
    "mayowa.falade@andela.com",
    "maryam.babalola@andela.com",
    "mel.michael@andela.com",
    "mirabel.ekwenugo@andela.com",
    "modupe.durosinmi-etti@andela.com",
    "mohini.ufeli@andela.com",
    "mustapha.abokede@andela.com",
    "nadayar@andela.com",
    "nengi.adoki@andela.com",
    "obioma.ofoamalu@andela.com",
    "oladayo.oyelade@andela.com",
    "oladipupo.isola@andela.com",
    "olaide.agboola@andela.com",
    "olaide.ojewale@andela.com",
    "olajide.aderibigbe@andela.com",
    "oladimeji.olajumoke@andela.com",
    "aliyu.abdullahi@andela.com",
    "olalekan.sogunle@andela.com",
    "olatoyosi.famakinde@andela.com",
    "olatunbosun.olanrewaju@andela.com",
    "garuba.olatunde@andela.com",
    "oduye.oluwaemisi@andela.com",
    "yinka.makanjuola@andela.com",
    "dara.oladosu@andela.com",
    "olufunmilade.oshodi@andela.com",
    "ladi.adenusi@andela.com",
    "olumuyiwa.osiname@andela.com",
    "daisi.sowemimo@andela.com",
    "oluwadamilola.adebayo@andela.com",
    "oluwafemi.sule@andela.com",
    "gbenga@andela.com",
    "oluwaseun.martins@andela.com",
    "talabi.oluwaseyi@andela.com",
    "oluwatoni.sodara@andela.com",
    "tosin.adesanya@andela.com",
    "oluwatosin.adesanya@andela.com",
    "oladele.oluwatoyin@andela.com ",
    "yetunde.sanni@andela.com ",
    "opeyemi.ogunjimi@andela.com ",
    "oreoluwa.akinniranye@andela.com ",
    "olarewaju.oreoluwa@andela.com ",
    "osmond.oranagwa@andela.com",
    "prosper.otemuyiwa@andela.com",
    "rukayat.sadiq@andela.com",
    "ruth.chukwumam@andela.com",
    "samuel.james@andela.com",
    "omeyinmi.sanni@andela.com",
    "sayo.alagbe@andela.com",
    "semiu.hassan@andela.com",
    "ayoola.solomon@andela.com",
    "ozioma.obiukwu@andela.com",
    "stephen.sunday@andela.com",
    "sulaimon.lasisi@andela.com",
    "sunday.adefila@andela.com",
    "surajudeen.akande@andela.com ",
    "susan.adelokiki@andela.com",
    "tams.sokari@andela.com",
    "amodu.temitope@andela.com",
    "terwase.gberikon@andela.com",
    "tobi.oduah@andela.com",
    "tolulope.komolafe@andela.com",
    "udo.nkwocha@andela.com",
    "ufedojo.opaluwa@andela.com",
    "uzo.awili@andela.com",
    "verem.dugeria@andela.com",
    "waleola.akinsanmi@andela.com",
    "wilson.omokoro@andela.com",
    "yusuf.daniju@andela.com"
    ],
  name: [
    "Abdulmalik Yusuf ",
    "Abimbola Idowu ",
    "Abiodun Shuaib ",
    "Abisoye Atolagbe ",
    "Adebayo Maborukoje ",
    "Adebayo Adepoju ",
    "Adeleke Togun ",
    "Ahmed Onawale ",
    "Ajibola Sogbein ",
    "Akeem Oduola ",
    "Akinjide Bankole ",
    "Akonam Ikpelue ",
    "Alex Obogbare ",
    "Oluwakamiye Adelemoni ",
    "Ayodeji Jayeoba ",
    "Babajide Bello ",
    "Babajide Fowotade ",
    "Babatunde Mustapha ",
    "Blessing Orazulume ",
    "Blessing Ebowe ",
    "Bodunde Adebiyi ",
    "Bosom Azibayanami  ",
    "Bukola Omotoso ",
    "Bukola Makinwa ",
    "Brice ",
    "Chibuzor Obiora ",
    "Chidi Ash ",
    "Chidebere Nwocha ",
    "Chidi Nnadi ",
    "ChidozieiIieomah ",
    "Chiemeka Alim ",
    "Kingsley Edeh ",
    "Chijioke Ndubisi ",
    "Chinedu Daniel ",
    "Damilola Omonori ",
    "Daniel James ",
    "Debbie Enomah ",
    "Dotun Owoade ",
    "Ebun ",
    "Emeka Ashikodi ",
    "Emeka Osuagwu ",
    "Emmanuel Akinyele ",
    "Emmanuel Chigbo ",
    "Emmanuel Isaac ",
    "Eniola Arinde ",
    "Tolulope Awoyemi ",
    "Faical Tchirou ",
    "Fiyinfoluwa Adebayo  ",
    "Florence Okosun ",
    "Franklin Ugwu  ",
    "Gbolahan Okerayi  ",
    "Gift Arisah  ",
    "Godson Ukpere ",
    "George James ",
    "Helen Eboagwu ",
    "Ibraheem Adeniyi ",
    "Ifeanyi Oraelosi ",
    "Ifedapo Olarewaju ",
    "Ikem Okonkwo ",
    "Ikenna Ekechi ",
    "Innocent Amadi ",
    "Issa Jubril ",
    "Iyanu Durotola ",
    "E ",
    "Johnson Ejezie ",
    "Joshua Ugba ",
    "Kayode Adeniyi ",
    "Kehinde Ogunde ",
    "Omowunmi Oni ",
    "Kehinde Shittu ",
    "Kolawole Erinoso ",
    "Kosy Anyanwu ",
    "Lawrence Bolutife ",
    "Mayowa Falade ",
    "Maryam Babalola ",
    "Mel Michael ",
    "Mirabel Ekwenugo ",
    "Modupe Durosinmi-Etti ",
    "Mohini Ufeli ",
    "Mustapha Abokede ",
    "Nadayar ",
    "Nengi Adoki ",
    "Obioma Ofoamalu ",
    "Oladayo Oyelade ",
    "Oladipupo Isola ",
    "Olaide Agboola ",
    "Olaide Ojewale ",
    "Olajide Aderibigbe ",
    "Oladimeji Olajumoke ",
    "Aliyu Abdullahi ",
    "Olalekan Sogunle ",
    "Olatoyosi Famakinde ",
    "Olatunbosun Olanrewaju ",
    "Garuba Olatunde ",
    "Oduye Oluwaemisi ",
    "Yinka Makanjuola ",
    "Dara Oladosu ",
    "Olufunmilade Oshodi ",
    "Ladi Adenusi ",
    "Olumuyiwa Osiname ",
    "Daisi Sowemimo ",
    "Oluwadamilola Adebayo ",
    "Oluwafemi Sule ",
    "Gbenga ",
    "Oluwaseun Martins ",
    "Talabi Oluwaseyi ",
    "Oluwatoni Sodara ",
    "Tosin Adesanya ",
    "Oluwatosin Adesanya ",
    "Oladele Oluwatoyin  ",
    "Yetunde Sanni  ",
    "Opeyemi Ogunjimi  ",
    "Oreoluwa Akinniranye  ",
    "Olarewaju Oreoluwa  ",
    "Osmond Oranagwa ",
    "Prosper Otemuyiwa ",
    "Rukayat Sadiq ",
    "Ruth Chukwumam ",
    "Samuel James ",
    "Omeyinmi Sanni ",
    "Sayo Alagbe ",
    "Semiu Hassan ",
    "Ayoola Solomon ",
    "Ozioma Obiukwu ",
    "Stephen Sunday ",
    "Sulaimon Lasisi ",
    "Sunday Adefila ",
    "Surajudeen Akande  ",
    "Susan Adelokiki ",
    "Tams Sokari ",
    "Amodu Temitope ",
    "Terwase Gberikon ",
    "Tobi Oduah ",
    "Tolulope Komolafe ",
    "Udo Nkwocha ",
    "Ufedojo Opaluwa ",
    "Uzo Awili ",
    "Verem Dugeria ",
    "Waleola Akinsanmi ",
    "Wilson Omokoro ",
    "Yusuf Daniju "
    ]
}

users[:email].length.times do |index|
  User.create(name: users[:name][index], email: users[:email][index])
end
