# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Category.destroy_all

all_categories = {
  title: [
    "Happy Camper",
    "Dewey Decimal",
    "The Whisper",
    "Megaphone",
    "Sharp Acid",
    "The Madea",
    "Carpe Diem",
    "Oliver Twist",
    "Caffeinator",
    "Incinerator",
    "Silly String",
    "The Finicky",
    "Guru",
    "Aljazeera",
    "Spiffy style",
    "Champagne",
    "Social butterfly",
    "The Sunrise",
    "The Melancholic",
    "Ironic Clown",
    "Browserify",
    "Bombster",
    "Wikipedia",
    "Polyglot",
    "First Responder",
    "MMM",
    "Night Owl",
    "Brown Envelope",
    "Typist",
    "Bouncer"
  ],
  desc: [
    "Someone who never fails to have a smile on his or her face",
    "Most Well Organized",
    "Someone whose voice is hardly heard",
    "Someone that you always hear",
    "Someone whose remarks are always marked by sarcasm",
    "Someone who is dramatic over everything and anything",
    "For making the most of every day",
    "Someone who wants more of everything (Good or Bad)",
    "For the employee who drinks most coffee in a day",
    "For being ready to eat and drink anything",
    "For being the office prankster",
    "For being particular about their things",
    "For always getting us out of a difficult situation",
    "Someone who is always up to date with events around the world (News man)",
    "For appearing dapper most times",
    "For most sparkling personality",
    "For constantly surfing and tweeting",
    "First to get to the office",
    "Someone who is difficult to tell when he's happy or sad",
    "Someone who thinks he's funny but he's not",
    "Someone that spends all time surfing the internet",
    "Someone that photobombs almost all pictures",
    "For always having an answer to all questions",
    "Someone who has worked with almost all stacks",
    "For being the first to react on anything on Slack",
    "For investing in anything that brings money",
    "Someone who works till very late in the night",
    "For being the best at keeping secrets",
    "For the fastest typer",
    "Someone who is known to go to the gym always and has something to show for it"
  ],
  imageUrl: [
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776659/happy-camper_uzmukj.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776660/organized_znvzug.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466896500/whisper_ajlvlw.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466898785/megaphone_zxihbg.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466898614/sarcasm_sypwig.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776660/dramatic_o8apy5.png",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466894755/hardworker_myhcj3.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776661/oliver_w0tf2q.png",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776659/coffee-guy_f6ganj.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466894755/incinerator_qfqwyj.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776661/silly_bt2v16.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466894754/finicky-eater_e6h5bw.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776660/guru_kvfsbs.png",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466899059/news_ffc9c2.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466894754/dapper_tzqoog.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1481894893/sparkling_jlhmsu.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466894756/social_butterfly_ik9i5w.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1466894754/sunrise_dv6rrc.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776659/face_po1lr5.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1464776659/not_funny_d7xttu.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1481892017/browserify_fb8wnk.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1481892402/bomber_kgv3oo.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1481892018/wikipedia_i9eqwv.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1481892017/polyglot_aoj0jv.png",
    "http://res.cloudinary.com/kaybaba/image/upload/v1481892017/first-responder_gzljfd.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1481892017/mmm_qfozax.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1481892017/owl_uqtjct.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1481892018/secret_crerwy.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1481892019/typist_kdtlcm.jpg",
    "http://res.cloudinary.com/kaybaba/image/upload/v1481892017/bouncer_joldfo.jpg"
  ]
}

all_categories[:title].length.times do |index|
  Category.create(title: all_categories[:title][index], short_description: all_categories[:desc][index], imageUrl: all_categories[:imageUrl][index])
end


User.destroy_all
Vote.destroy_all

users = {
  email: [
    "aliyu.abdullahi@andela.com",
    "abdulmalik.abdulwahab@andela.com",
    "femi.abolaji@andela.com",
    "fiyinfoluwa.adebayo@andela.com",
    "oluwadamilola.adebayo@andela.com",
    "bodunde.adebiyi@andela.com",
    "sunday.adefila@andela.com",
    "oluwatosin.adegbaju@andela.com",
    "mayowa.adegbola@andela.com",
    "seyi.adekoya@andela.com",
    "susan.adelokiki@andela.com",
    "sadiq.ademosu@andela.com",
    "kayode.adeniyi@andela.com",
    "ibraheem.adeniyi@andela.com",
    "ladi.adenusi@andela.com",
    "adebayo.adepoju@andela.com",
    "olajide.aderibigbe@andela.com",
    "adebayo.adesanya@andela.com",
    "adeyemi.adesanya@andela.com",
    "tosin.adesanya@andela.com",
    "jolaade.adewale@andela.com",
    "adewale.fadahunsi@andela.com",
    "adimoranma.felix@andela.com",
    "olaide.agboola@andela.com",
    "oreoluwa.agunbiade@andela.com",
    "ademola.raimi@andela.com",
    "opeyemi.ahmed@andela.com",
    "surajudeen.akande@andela.com",
    "oreoluwa.akinniranye@andela.com",
    "waleola.akinsanmi@andela.com",
    "olawale.akinseye@andela.com",
    "emmanuel.akinyele@andela.com",
    "raphael.akpan@andela.com",
    "kesiena.akpobome@andela.com",
    "kolawole.alade@andela.com",
    "olawale.aladeusi@andela.com",
    "sayo.alagbe@andela.com",
    "uche.albert@andela.com",
    "muhammed.ali@andela.com",
    "chiemeka.alim@andela.com",
    "innocent.amadi@andela.com",
    "amodu.temitope@andela.com",
    "annabelle.amotsuka@andela.com",
    "kosy.anyanwu@andela.com",
    "jorg.are@andela.com",
    "emeka.ashikodi@andela.com",
    "chidi.ash@andela.com",
    "abdulsemiu.atanda@andela.com",
    "atolagbe.bisoye@andela.com",
    "uzo.awili@andela.com",
    "tolulope.awoyemi@andela.com",
    "shalom.ayidu@andela.com",
    "joshua.azemoh@andela.com",
    "maryam.babalola@andela.com",
    "omodemilade.bamgbose@andela.com",
    "kehinde.banasko@andela.com",
    "akinjide.bankole@andela.com",
    "oreoluwa.banwo@andela.com",
    "winner-timothy.bolorunduro@andela.com",
    "emmanuel.chigbo@andela.com",
    "chijioke.elisha-wigwe@andela.com",
    "ezinne.chimah@andela.com",
    "chineze.nwosu@andela.com",
    "daniel.okocha@andela.com",
    "chinedu.daniel@andela.com",
    "yusuf.daniju@andela.com",
    "chukwuerika.dike@andela.com",
    "verem.dugeri@andela.com",
    "babajide.duroshola@andela.com",
    "modupe@andela.com",
    "iyanu.durotola@andela.com",
    "helen.eboagwu@andela.com",
    "blessing.ebowe@andela.com",
    "ebun@andela.com",
    "johnson.ejezie@andela.com",
    "rowland.ekemezie@andela.com",
    "fortune.ekeruo@andela.com",
    "priscilla.ekhator@andela.com",
    "mirabel.ekwenugo@andela.com",
    "uyiosa.enabulele@andela.com",
    "murphy.enaho@andela.com",
    "nadayar@andela.com",
    "shalom.ayidu@andela.com",
    "deborah.enomah@andela.com",
    "kolawole.erinoso@andela.com",
    "susan.esho@andela.com",
    "olalekan.eyiowuawi@andela.com",
    "ngozi.ekweke@andela.com",
    "chukwuma.ezumezu@andela.com",
    "mayowa.falade@andela.com",
    "olatoyosi.famakinde@andela.com",
    "segun.famisa@andela.com",
    "terwase.gberikon@andela.com",
    "gozie.nwolisa@andela.com",
    "hassan.oyeboade@andela.com",
    "hassan.ayomon@andela.com",
    "abiola.ibrahim@andela.com",
    "bosom.igere@andela.com",
    "chidozie.ijeomah@andela.com",
    "ikem.okonkwo@andela.com",
    "akonam@andela.com",
    "kenny.isichei@andela.com",
    "oladipupo.isola@andela.com",
    "israel.tomilayo@andela.com",
    "oyebanji.jacob@andela.com",
    "george.james@andela.com",
    "samuel.james@andela.com",
    "daniel.james@andela.com",
    "abdulmujeeb.jamiu@andela.com",
    "issa.jubril@andela.com",
    "taiwo@andela.com",
    "tolulope.komolafe@andela.com",
    "kuti.gbolahan@andela.com",
    "damilare.lana@andela.com",
    "sulaimon.lasisi@andela.com",
    "adebayo.maborukoje@andela.com",
    "yinka.makanjuola@andela.com",
    "bukola.makinwa@andela.com",
    "oluwaseun.martins@andela.com",
    "mayowa.pitan@andela.com",
    "michael.egwali@andela.com",
    "mel.michael@andela.com",
    "michael.ogala@andela.com",
    "morolake.orekoya@andela.com",
    "chijioke.ndubisi@andela.com",
    "philip.newman@andela.com",
    "brice@andela.com",
    "victor.nwaiwu@anela.com",
    "chukwuemeka.nwankwo@andela.com",
    "chidiebere.nwokocha@andela.com",
    "chibuzor.obiora@andela.com",
    "tobi.oduah@andela.com",
    "akeem.oduola@andela.com",
    "oduye.oluwayemisi@andela.com",
    "obioma.ofoamalu@andela.com",
    "godwin.onisofien@andela.com",
    "kehinde.ogunde@andela.com",
    "suliat.ogunlende@andela.com",
    "olaide.ojewale@andela.com",
    "abisoye.oke-lawal@andela.com",
    "gbolahan.okerayi@andela.com",
    "florence.okosun@andela.com",
    "femi.oladeji@andela.com",
    "oladimeji.olajumoke@andela.com",
    "dara.oladosu@andela.com",
    "azeez.olaniran@andela.com",
    "olarewaju.oreoluwa@andela.com",
    "cyril.paul@andela.com",
    "temitope.olotin@andela.com",
    "oreofeoluwapo.olutola@andela.com",
    "femi.senjobi@andela.com",
    "celestine.omin@andela.com",
    "wilson.omokoro@andela.com",
    "bukola.omotoso@andela.com",
    "ahmed.onawale@andela.com",
    "oni.omowunmi@andela.com",
    "daniel.onodje@andela.com",
    "ufedojo.opaluwa@andela.com",
    "osmond.oranagwa@andela.com",
    "blessing.orazulume@andela.com",
    "olufunmilade.oshodi@andela.com",
    "olumuyiwa.osiname@andela.com",
    "gbenga@andela.com",
    "derin.otegbola@andela.com",
    "dotun.owoade@andela.com",
    "benjamin.owobu@andela.com",
    "rukayat.sadiq@andela.com",
    "yetunde.sanni@andela.com",
    "omeyinmi.sanni@andela.com",
    "shittu.adedamola@andela.com",
    "abiodun.shuaib@andela.com",
    "simon.peter@andela.com",
    "tobi.smith@andela.com",
    "ajibola.sogbein@andela.com",
    "tams.sokari@andela.com",
    "oluwatoni.sodara@andela.com",
    "moyosore.sosan@andela.com",
    "stephen.oduntan@andela.com",
    "oluwafemi.sule@andela.com",
    "seni@andela.com",
    "sunday.nwuguru@andela.com",
    "stephen.sunday@andela.com",
    "talabi.oluwaseyi@andela.com",
    "faical.tchirou@andela.com",
    "temitope.fowotade@andela.com",
    "tijesunimi.peters@andela.com",
    "adeleke.togun@andela.com",
    "mohini.ufeli@andela.com",
    "joshua.ugba@andela.com",
    "chioma.uzo-kalu@andela.com",
    "joy.uzosike@andela.com",
    "abdulmalik.yusuf@andela.com"
  ],
  name: [
    "Abdullahi Aliyu",
    "Abdulmalik  Abdbulwahab",
    "Abolaji Femi",
    "Adebayo Fiyinfoluwa",
    "Adebayo Oluwadamilola",
    "Adebiyi Bodunde",
    "Adefila  Sunday",
    "Adegbaju Oluwatosin",
    "Adegbola Mayowa",
    "Adekoya Seyi",
    "Adelokiki Susan",
    "Ademosu Sadiq ",
    "Adeniyi Kayode",
    "Adeniyi  Ibraheem",
    "Adenusi Olumuyiwa Ladi",
    "Adepoju Adebayo",
    "Aderibigbe Olajide",
    "Adesanya Adebayo ",
    "Adesanya Tosin Matthew",
    "Adesanya  Oluwatosin",
    "Adewale Jolaade",
    "Adewale Fadahunsi",
    "Adimoranma  Felix Nwocha",
    "Agboola Olaide",
    "Agunbiade Oreoluwa",
    "Ademola Raimi",
    "Ahmed Opeyemi",
    "Akande  Surajudeen",
    "Akinniranye  Oreoluwa",
    "Akinsanmi Waleola",
    "Akinseye Olawale",
    "Akinyele Emmanuel",
    "Akpan Raphael",
    "Akpobome Kesiena",
    "Alade Kolawole",
    "Aladeusi Olawale",
    "Alagbe Olusayo",
    "Albert Uche",
    "Ali Muhammed",
    "Alim Chiemeka ",
    "Amadi Innocent",
    "Amodu Temitope",
    "Amotsuka Annabelle",
    "Anyanwu  Kosisochukwu",
    "Are Jorg",
    "Ashikodi Emeka ",
    "Ashimole Chidi",
    "Atanda Abdulsemiu",
    "Atolagbe  Bisoye",
    "Awili Uzo",
    "Awoyemi Ezekiel",
    "Ayidu Shalom",
    "Azemoh Joshua",
    "Babalola Maryam",
    "Bamgbose Omodemilade",
    "Banasko Kehinde",
    "Bankole Akinjide",
    "Banwo Oreoluwa",
    "Bolorunduro  Winner-Timothy",
    "Chigbo Emmanuel",
    "Chijioke Elisha-Wigwe ",
    "Chimah Ezinne",
    "Chineze Nwosu",
    "Daniel Okocha",
    "Daniel  Chinedu",
    "Daniju Yusuf  Omokayode",
    "Dike Chukwuerika",
    "Dugeri Verem",
    "Duroshola Babajide",
    "Durosinmi-Etti Modupe",
    "Durotola  Iyanu-Tomiwa",
    "Eboagwu Helen ",
    "Ebowe  Blessing",
    "Ebunoluwa Omoni",
    "Ejezie Johnson",
    "Ekemezie Rowland",
    "Ekeruo Fortune",
    "Ekhator Priscilla ",
    "Ekwenugo Mirabel",
    "Enabulele Uyiosa",
    "Enaho Murphy",
    "Enegesi Nadayar",
    "Enogwe Victor",
    "Enomah Deborah",
    "Erinoso Kolawole",
    "Esho Oluwafunmilayo",
    "Eyiowuawi Olalekan",
    "Ezekwe Ngozi",
    "Ezumezu  Anselm",
    "Falade Mayowa",
    "Famakinde Olatoyosi ",
    "Famisa Segun",
    "Gberikon Terwase ",
    "Gozie Nwolisa",
    "Hassan Oyeboade",
    "Hassan  Semiu Ayomon",
    "Ibrahim Abiola",
    "Igere Bosom",
    "Ijeomah Chidozie",
    "Ikem  Okonkwo",
    "Ikpelue Akonam",
    "Isichei Kenny",
    "Isola  Oladipupo",
    "Israel Tomilayo",
    "Jacob  Oyebanji",
    "James George",
    "James Samuel",
    "James  Daniel",
    "Jamiu Abdulmujeeb",
    "Jubril  Issa",
    "Judah-Ajayi Taiwo ",
    "Komolafe Tolulope",
    "Kuti  Gbolahan",
    "Lana Damilare",
    "Lasisi Sulaimon",
    "Maborukoje Adebayo",
    "Makanjuola Yinka",
    "Makinwa Bukola",
    "Martins Oluwaseun",
    "Mayowa Pitan",
    "Michael Egwali",
    "Michael Mel",
    "Michael  Ogala",
    "Morolake Orekoya",
    "Ndubisi  Chijioke",
    "Newman Philip",
    "Nkengsa Brice",
    "Nwaiwu Victor",
    "Nwankwo  Chukwuemeka ",
    "Nwokocha  Chidiebere",
    "Obiora Chibuzor",
    "Oduah  Tobi",
    "Oduola Akeem",
    "Oduye  Oluwayemisi",
    "Ofoamalu Obioma",
    "Ogbara  Onisofien",
    "Ogunde Kehinde",
    "Ogunlende Suliat",
    "Ojewale Olaide",
    "Oke-lawal Abisoye",
    "Okerayi Gbolahan",
    "Okosun Florence",
    "Oladeji Femi",
    "Oladimeji  Olajumoke ",
    "Oladosu Dara",
    "Olaniran Azeez",
    "Olarewaju Oreoluwa",
    "Ologho Paul Cyril",
    "Olotin Temitope",
    "Olutola  Oreofeoluwapo",
    "Oluwafemi Senjobi",
    "Omin Celestine",
    "Omokoro  Wilson",
    "Omotoso Bukola",
    "Onawale Ahmed",
    "Oni  Kehinde",
    "Onodje Daniel",
    "Opaluwa Ufedojo",
    "Oranagwa Osmond",
    "Orazulume  Blessing",
    "Oshodi  Olufunmilade",
    "Osiname  Olumuyiwa",
    "Osowe Oluwagbenga",
    "Otegbola Derin",
    "Owoade Dotun",
    "Owobu Benjamin",
    "Sadiq  Rukayat",
    "Sanni  Oluwatoyin",
    "Sanni  Omeyimi",
    "Shittu  Kehinde",
    "Shuaib Abiodun",
    "Simon Peter Damian",
    "Smith Tobi",
    "Sogbein  Ajibola",
    "Sokari Tams",
    "Solarin-Sodara  Oluwatoni",
    "Sosan Moyosore",
    "Stephen Oduntan",
    "Sule Oluwafemi",
    "Sulyman Seni",
    "Sunday Nwuguru",
    "Sunday Stephen ",
    "Talabi  Oluwaseyi",
    "Tchirou Faiçal",
    "Temitope Fowotade",
    "Tijesunimi Peters",
    "Togun Adeleke",
    "Ufeli Mohini",
    "Ugba  Joshua ",
    "Uzo-Kalu Chioma",
    "Uzosike Uzoamaka",
    "Yusuf  Abdulmalik"
  ]
}

users[:email].length.times do |index|
  User.create(name: users[:name][index], email: users[:email][index])
end
